"use client";

import React, { useState, useEffect } from "react";
import { useAuth } from "@/context/AuthContext";
import { useRouter } from "next/navigation";
import Navbar from "@/components/layout/Navbar";
import { 
  Users, 
  Wallet, 
  Copy, 
  Share2, 
  Award,
  Ticket,
  Printer,
  Plus,
  TrendingUp,
  ShieldCheck,
  ChevronRight
} from "lucide-react";
import toast from "react-hot-toast";
import { db } from "@/lib/firebase";
import { collection, query, where, getDocs, addDoc, serverTimestamp, doc, getDoc } from "firebase/firestore";
import jsPDF from "jspdf";
import { cn } from "@/lib/utils";

export default function AgentDashboard() {
  const { user, profile } = useAuth();
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [coupons, setCoupons] = useState<any[]>([]);
  const [redemptions, setRedemptions] = useState(0);

  const isStorefrontAgent = profile?.role === "storefront_agent";

  useEffect(() => {
    // If user is loaded and not an agent, redirect to application
    if (profile && !profile.agentStatus) {
      router.push("/agent/apply");
    } else if (profile) {
      fetchAgentData();
      setLoading(false);
    }
  }, [profile, router]);

  const fetchAgentData = async () => {
    if (!user) return;
    // Fetch coupons generated by this agent
    const q = query(collection(db, "coupons"), where("createdBy", "==", user.uid));
    const snapshot = await getDocs(q);
    setCoupons(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })));
    
    // Count redemptions (mocked for now, would be a real query)
    setRedemptions(4); // e.g. 4 coupons used so far
  };

  const generateCoupons = async (count: number = 10) => {
    if (!user) return;
    setLoading(true);
    try {
      const newCoupons = [];
      for (let i = 0; i < count; i++) {
        const code = `BY-${user.uid.slice(0, 4)}-${Math.random().toString(36).substring(2, 6).toUpperCase()}`;
        const couponData = {
          code,
          type: "storefront_discount",
          value: 500,
          createdBy: user.uid,
          status: "active",
          createdAt: serverTimestamp(),
          redeemedBy: null
        };
        await addDoc(collection(db, "coupons"), couponData);
        newCoupons.push(couponData);
      }
      toast.success(`Generated ${count} coupons!`);
      fetchAgentData();
    } catch (err: any) {
      toast.error(err.message);
    } finally {
      setLoading(false);
    }
  };

  const printCoupons = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text("BYLYF STOREFRONT COUPONS", 20, 20);
    doc.setFontSize(12);
    doc.text(`Agent: ${profile?.displayName} | ₹500 Discount`, 20, 30);
    doc.line(20, 35, 190, 35);

    let y = 50;
    coupons.filter(c => c.status === "active").forEach((coupon, index) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.rect(20, y, 170, 30);
      doc.setFont("helvetica", "bold");
      doc.text(`CODE: ${coupon.code}`, 30, y + 15);
      doc.setFont("helvetica", "normal");
      doc.text("Redeem on bylyf.com | Max 6 per user", 30, y + 23);
      doc.text("₹500 OFF", 160, y + 18);
      y += 40;
    });

    doc.save("BYLYF-Storefront-Coupons.pdf");
  };

  if (loading) return <div className="min-h-screen flex items-center justify-center font-black">LOADING AGENT PORTAL...</div>;

  return (
    <main className="min-h-screen bg-background">
      <Navbar />

      <div className="max-w-7xl mx-auto px-4 py-12">
        <div className="flex flex-col md:flex-row justify-between items-end mb-12 gap-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-primary/10 text-primary rounded-full text-xs font-black uppercase tracking-widest mb-4">
              <Award className="w-4 h-4" />
              {isStorefrontAgent ? "Premium Storefront Agent" : "Referral Agent"}
            </div>
            <h1 className="text-4xl font-black tracking-tight">Agent Workspace</h1>
            <p className="text-muted-foreground mt-2">Manage your {isStorefrontAgent ? "Storefront Coupons" : "Referral Links"} and track milestones.</p>
          </div>
          
          <div className="flex gap-4">
            {isStorefrontAgent && (
              <button 
                onClick={() => generateCoupons(10)}
                className="px-6 py-3 bg-primary text-primary-foreground rounded-2xl font-bold flex items-center gap-2 shadow-lg shadow-primary/20 hover:scale-105 transition-all"
              >
                <Plus className="w-5 h-5" />
                Generate Batch
              </button>
            )}
            <button className="px-6 py-3 bg-secondary text-foreground rounded-2xl font-bold">
              Withdraw Earnings
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Main Stats Area */}
          <div className="lg:col-span-8 space-y-8">
            
            {/* Storefront Milestone Card */}
            {isStorefrontAgent && (
              <div className="bg-primary text-primary-foreground rounded-[3rem] p-10 relative overflow-hidden shadow-2xl shadow-primary/20">
                <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full -translate-y-1/2 translate-x-1/2 blur-3xl"></div>
                <div className="relative z-10">
                  <h3 className="text-2xl font-black mb-6">Commission Milestone</h3>
                  <div className="flex justify-between items-end mb-4">
                    <div>
                      <div className="text-4xl font-black">{redemptions % 6} / 6</div>
                      <div className="text-xs font-bold uppercase tracking-widest opacity-60">Redemptions in current cycle</div>
                    </div>
                    <div className="text-right">
                      <div className="text-xl font-black">₹3,000</div>
                      <div className="text-xs font-bold uppercase tracking-widest opacity-60">Target Payout</div>
                    </div>
                  </div>
                  <div className="h-3 bg-white/10 rounded-full overflow-hidden p-0.5 border border-white/10">
                    <div 
                      className="h-full bg-white rounded-full transition-all duration-1000" 
                      style={{ width: `${((redemptions % 6) / 6) * 100}%` }}
                    ></div>
                  </div>
                  <p className="mt-6 text-sm font-medium opacity-80">
                    You get a commission payout every time 6 of your coupons are successfully redeemed.
                  </p>
                </div>
              </div>
            )}

            {/* Coupon List / Inventory */}
            {isStorefrontAgent && (
              <div className="bg-secondary/30 rounded-[3rem] border border-border p-8">
                <div className="flex justify-between items-center mb-8">
                  <h3 className="text-xl font-black flex items-center gap-2">
                    <Ticket className="w-6 h-6 text-primary" />
                    Coupon Inventory
                  </h3>
                  <button 
                    onClick={printCoupons}
                    disabled={coupons.length === 0}
                    className="px-4 py-2 bg-background border border-border rounded-xl text-xs font-black uppercase tracking-widest flex items-center gap-2 hover:bg-secondary transition-colors disabled:opacity-50"
                  >
                    <Printer className="w-4 h-4" />
                    Print PDF
                  </button>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
                  {coupons.slice(0, 9).map((coupon, i) => (
                    <div key={i} className="p-4 bg-background rounded-2xl border border-border flex flex-col items-center justify-center text-center">
                      <div className="text-xs font-black font-mono text-primary mb-1">{coupon.code}</div>
                      <div className={cn(
                        "text-[8px] font-black uppercase tracking-widest px-2 py-0.5 rounded-full",
                        coupon.status === "active" ? "bg-success/10 text-success" : "bg-muted text-muted-foreground"
                      )}>
                        {coupon.status}
                      </div>
                    </div>
                  ))}
                  {coupons.length > 9 && (
                    <div className="p-4 bg-secondary/30 rounded-2xl border border-dashed border-border flex items-center justify-center text-xs font-black text-muted-foreground">
                      +{coupons.length - 9} More
                    </div>
                  )}
                  {coupons.length === 0 && (
                    <div className="col-span-full py-12 text-center text-muted-foreground italic text-sm">
                      No coupons generated yet. Click "Generate Batch" to start.
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Standard Referral Section */}
            {!isStorefrontAgent && (
              <div className="bg-secondary/30 rounded-[2.5rem] border border-border p-8">
                <h3 className="text-xl font-black mb-6">Referral Link</h3>
                <div className="flex gap-4">
                  <input 
                    type="text" 
                    readOnly 
                    value={`https://bylyf.com?ref=${user?.uid.slice(0, 8)}`}
                    className="flex-1 bg-background border border-border rounded-xl px-4 py-3 font-bold text-sm"
                  />
                  <button onClick={() => toast.success("Link copied!")} className="p-3 bg-primary text-primary-foreground rounded-xl">
                    <Copy className="w-5 h-5" />
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Right Sidebar: Quick Stats */}
          <div className="lg:col-span-4 space-y-8">
            <div className="bg-secondary/30 border border-border rounded-[3rem] p-8">
              <h3 className="text-lg font-black mb-6 uppercase tracking-widest">Earnings Summary</h3>
              <div className="space-y-6">
                <div className="flex justify-between items-center">
                  <div className="text-sm font-bold text-muted-foreground">Pending Payout</div>
                  <div className="text-xl font-black">₹0.00</div>
                </div>
                <div className="flex justify-between items-center">
                  <div className="text-sm font-bold text-muted-foreground">Total Earned</div>
                  <div className="text-xl font-black">₹12,450</div>
                </div>
                <div className="pt-6 border-t border-border">
                  <div className="flex items-center gap-3 text-xs font-bold text-primary mb-4">
                    <TrendingUp className="w-4 h-4" />
                    Performance +12% this month
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-secondary/30 border border-border rounded-[3rem] p-8">
              <h3 className="text-lg font-black mb-6 uppercase tracking-widest">Recent Redemptions</h3>
              <div className="space-y-4">
                <div className="text-center py-8 text-muted-foreground italic text-sm">
                  No recent redemptions yet.
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </main>
  );
}
